package com.example.indonesiapower.ui.kategori.tambah

import android.os.Bundle
import android.view.View
import android.widget.ImageButton
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import com.example.indonesiapower.R
import com.example.indonesiapower.databinding.ActivityTambahKategoriBinding
import com.google.android.material.textfield.TextInputEditText
import java.text.SimpleDateFormat
import java.util.*

class TambahKategoriActivity : AppCompatActivity() {

    private lateinit var binding: ActivityTambahKategoriBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        binding = ActivityTambahKategoriBinding.inflate(layoutInflater)
        setContentView(binding.root)
        supportActionBar?.hide()

        setupUI()
        setupAutoGeneratedFields()
        setupListeners()
    }

    private fun setupUI() {
        // Status bar
        window.statusBarColor = resources.getColor(R.color.white, theme)
        window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
    }

    private fun setupAutoGeneratedFields() {
        // Generate random category code
        val randomKode = "KTG-${UUID.randomUUID().toString().substring(0, 5).uppercase()}"
        binding.etKodeKategori.setText(randomKode)

        // Set current date
        val dateFormat = SimpleDateFormat("dd-MM-yyyy", Locale.getDefault())
        binding.etDibuatTanggal.setText(dateFormat.format(Date()))
    }

    private fun setupListeners() {
        binding.btnKembali.setOnClickListener { finish() }

        binding.btnSimpan.setOnClickListener {
            if (validateForm()) {
                saveCategory()
            }
        }
    }

    private fun validateForm(): Boolean {
        return when {
            binding.etNamaKategori.text.isNullOrBlank() -> {
                binding.etNamaKategori.error = "Nama kategori harus diisi"
                false
            }
            binding.etNamaKategori.text.toString().length < 3 -> {
                binding.etNamaKategori.error = "Nama kategori terlalu pendek"
                false
            }
            else -> true
        }
    }

    private fun saveCategory() {
        val categoryData = mapOf(
            "kode_kategori" to binding.etKodeKategori.text.toString(),
            "nama_kategori" to binding.etNamaKategori.text.toString(),
            "dibuat_tgl" to binding.etDibuatTanggal.text.toString()
        )

        // Here you would normally make API call
        // For now we'll just show a toast
        Toast.makeText(
            this,
            "Kategori ${binding.etNamaKategori.text} berhasil disimpan",
            Toast.LENGTH_SHORT
        ).show()

        finish()
    }
}